MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/path/to/.cache/torch/checkpoints/resnet50-19c8e357.pth' # from https://download.pytorch.org/models/resnet50-19c8e357.pth
  NAME: 'resnet50'
  GENERALIZED_MEAN_POOL: 'off'
  REDUCE_DIM: 'off'
  REDUCED_DIM: 2048
  CENTER_LOSS: 'on'
  CENTER_FEAT_DIM: 2048
  TRIPLET_LOSS: 'on'
  WEIGHT_REGULARIZED_TRIPLET: 'on'
  CLASS_TRIPLET_LOSS: 'off'
  HIERARCHICAL_CLS: 'off'
  AAM_LOSS: 'off'
  CIRCLE_LOSS: 'off'

INPUT:
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  IMG_SIZE: [128, 128]
  PROB: 0.5
  V_PROB: 0.0
  P_PROB: 0.0
  ROTATE: 'off'
  ROTATION: 90
  RE_PROB: 0.0
  CROP: 'on'
  PADDING: 10

DATASETS:
  NAMES: ('co3d_reid_v4')   # without car and stopsign

DATALOADER:
  NUM_WORKERS: 8
  PK_SAMPLER: 'on'
  NUM_INSTANCE: 4
  CLASS_SAMPLER: 'off'
  NUM_CLASS: 4
  CLASS_BALANCED_SAMPLER: 'off'

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 12
  BASE_LR: 0.00007

  MARGIN: 0.3
  CLASS_MARGIN: 0.5
  MARGIN_CLS: 0.5
  SCALE: 64

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [4, 7]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 1
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 1  # in epochs
  LOG_PERIOD: 20        # in iterations
  EVAL_PERIOD: 1        # in epochs

TEST:
  IMS_PER_BATCH: 128
  WEIGHT: "path"
  FEAT_NORM: 'on'
  EVALUATE_ONLY: 'off'
  SAVE_MEMORY_BLOCK: 4096

INFERENCE:
 DO_INFERENCE: 'off'
 SAMPLES: 10
 NUM_RETRIEVE: 16
 OUTPUT: "file-path"

WANDB:
 LOG_WANDB: 'on'
 PROJECT: "Reverse_Pipeline"
 NOTES: ""
 TAGS: ["train", "co3d_reid_v4"]

OUTPUT_DIR: "./log/Reverse_Pipeline/co3d_reid_v4"
OUTPUT_VERSIONING: 'on'
